name: Crowdin upload

on:
  push:
    branches:
      - main
      - master

jobs:
  upload-to-crowdin:
    runs-on: [self-hosted, production]
    container: docker.tw.ee/actions_java17

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: crowdin action
        uses: crowdin/github-action@v1
        with:
          upload_sources: true
          upload_translations: false
          download_translations: false
          base_url: 'https://transferwise.crowdin.com'
          token: ${{ secrets.CROWDIN_ENTERPRISE_TOKEN }}
          project_id: ${{ secrets.CROWDIN_PROJECT_ID }}
